name: interpret-text
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - abseil-cpp=20211102.0
  - aiofiles=22.1.0
  - aiohttp=3.9.5
  - aiosignal=1.2.0
  - aiosqlite=0.18.0
  - annotated-types=0.6.0
  - ansicolors=1.1.8
  - anyio=4.6.2
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=14.0.2
  - asttokens=2.0.5
  - async-timeout=4.0.3
  - attrs=24.2.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.10.55
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - boost-cpp=1.82.0
  - boto3=1.34.154
  - botocore=1.34.154
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - cached-property=1.5.2
  - catalogue=2.0.10
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpathlib=0.16.0
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.1
  - confection=0.1.4
  - contourpy=1.2.0
  - cryptography=43.0.3
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - cycler=0.11.0
  - cymem=2.0.6
  - cyrus-sasl=2.1.28
  - cython-blis=0.7.9
  - dataclasses=0.8
  - datasets=2.19.1
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.8
  - distro=1.9.0
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - eval_type_backport=0.2.0
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.6.4
  - ffmpeg=4.3
  - filelock=3.13.1
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozenlist=1.5.0
  - fsspec=2024.3.1
  - gettext=0.21.0
  - gflags=2.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.2.1
  - gnutls=3.6.15
  - grpc-cpp=1.48.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h5py=3.12.1
  - hdf5=1.12.1
  - httpcore=1.0.2
  - httpx=0.27.0
  - huggingface_hub=0.24.6
  - icu=73.2
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.0
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - interpret-community=0.31.0
  - interpret-core=0.5.0
  - ipykernel=6.29.5
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - jiter=0.6.1
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter_client=7.4.9
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_fileid=0.9.0
  - jupyter_server_terminals=0.4.4
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.5
  - jupyterlab=3.6.8
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.27.3
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.9.1
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libebm=0.5.0
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libpq=17.2
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.46.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxgboost=2.1.1
  - libxkbcommon=1.0.3
  - libxml2=2.10.4
  - libzlib=1.2.13
  - lightgbm=4.5.0
  - llvmlite=0.36.0
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mistune=2.0.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ml-wrappers=0.5.5
  - multidict=6.1.0
  - multiprocess=0.70.15
  - murmurhash=1.0.7
  - mysql=8.4.0
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nbclassic=1.1.0
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - nltk=3.9.1
  - nodejs=16.20.2
  - notebook=6.5.7
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89.1
  - nteract-scrapbook=0.5.0
  - numba=0.53.1
  - numexpr=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openai=0.28.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openpyxl=3.1.5
  - openssl=3.4.0
  - orc=1.7.4
  - overrides=7.4.0
  - packaging=24.1
  - pandas=1.5.3
  - pandas-stubs=1.5.3.230203
  - pandocfilters=1.5.0
  - papermill=2.6.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.2
  - platformdirs=3.10.0
  - plotly=5.24.1
  - pluggy=1.5.0
  - ply=3.11
  - pooch=1.4.0
  - preshed=3.0.6
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.43
  - propcache=0.2.0
  - protobuf=3.20.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=2.1.1
  - pyarrow=14.0.2
  - pycparser=2.21
  - pydantic=1.10.19
  - pydantic-core=2.20.1
  - pygments=2.15.1
  - pyopenssl=24.2.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - pytest=7.4.4
  - python=3.9.21
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python-xxhash=2.0.2
  - python_abi=3.9
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytorch-pretrained-bert=0.6.2
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=24.0.1
  - qt=5.15.9
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - raiutils=0.4.2
  - re2=2022.04.01
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.9.11
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.10.6
  - s2n=1.3.27
  - s3transfer=0.10.1
  - sacremoses=0.0.43
  - safetensors=0.4.5
  - scikit-learn=1.5.1
  - scipy=1.10.1
  - scrapbook=0.5.0
  - send2trash=1.8.2
  - sentence-transformers=3.3.1
  - sentry-sdk=2.19.2
  - setproctitle=1.2.2
  - setuptools=75.1.0
  - shap=0.41.0
  - shellingham=1.5.0
  - sip=6.7.12
  - six=1.16.0
  - slicer=0.0.7
  - smart_open=5.2.1
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.45.3
  - srsly=2.4.8
  - stack_data=0.2.0
  - tbb=2020.3
  - tenacity=9.0.0
  - terminado=0.17.1
  - thinc=8.2.2
  - threadpoolctl=3.5.0
  - tiktoken=0.8.0
  - tinycss2=1.2.1
  - tk=8.6.14
  - tokenizers=0.20.1
  - tomli=2.0.1
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tornado=6.4.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - transformers=4.45.2
  - typer=0.9.0
  - types-pytz=2022.4.0.0
  - typescript=3.6.4
  - typing=3.10.0.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=1.26.19
  - utf8proc=2.6.1
  - wandb=0.18.7
  - wasabi=0.9.1
  - wcwidth=0.2.5
  - weasel=0.3.4
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - xgboost=2.1.1
  - xxhash=0.8.0
  - xz=5.4.6
  - y-py=0.6.2
  - yaml=0.2.5
  - yarl=1.18.0
  - ypy-websocket=0.8.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - en-core-web-sm==3.7.1
      - ipywidgets==8.1.5
      - jupyterlab-widgets==3.0.13
      - widgetsnbextension==4.0.13

